project/urls.py
from django.contrib import admin
from django.urls import path, include

from rate.views import (
    index, SearchView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax_select/', include('ajax_select.urls')),
    path('search/', SearchView.as_view(), name='search'),
    path('', index, name='index'),
]

rate/models.py
from django.db import models


class Uchastnik(models.Model):

    uchastnik = models.CharField(max_length=150, unique=True)

    @staticmethod
    def get_with_storonapodelu():
        return Uchastnik.objects \
            .annotate(
                storonapodelu_count=models.Count('storonapodelu')) \
            .exclude(
                storonapodelu_count=0)

    def __str__(self):
        return self.uchastnik


class StoronaPoDelu(models.Model):

    uchastnik = models.ForeignKey(
        Uchastnik, verbose_name='Участник', on_delete = models.CASCADE)

rate/forms.py
from django import forms
from django.db.models import Count
from ajax_select import make_ajax_field
from ajax_select.fields import AutoCompleteField

from .models import Uchastnik


class SearchUchastnikForm(forms.Form):
    search = AutoCompleteField(
        'uchastniki',
        required=True,
        help_text=None,
        plugin_options={'minLength': 3},
        min_length=3)

    def get_queryset(self):
        if not self.is_valid():
            return Uchastnik.objects.none()

        return Uchastnik \
            .get_with_storonapodelu() \
            .filter(uchastnik__istartswith=self.cleaned_data.get('search'))

rate/views.py
from django.views import View
from django.shortcuts import render

from .forms import SearchUchastnikForm
from .models import Uchastnik


def index(request):

    person_name = request.GET.get('person')
    return render(request, 'index.html', locals())


class SearchView(View):
    template_name = 'search.html'

    def post(self, request):

        form = SearchUchastnikForm(data=request.POST)
        return render(
            request,
            self.template_name,
            context={
                'search_uchastnik_form': form,
                'queryset': form.get_queryset(),
            })

templates/header.html
<form action="{% url 'search' %}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    {{ search_uchastnik_form.search }}
  </div>
  <input type="submit" value="Поиск" />
</form>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    {% block header %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Index{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{ search_uchastnik_form.media }}
    {% endblock %}
  </head>
  <body>
    {% if search_uchastnik_form %}
    {% include 'header.html' with search_uchastnik_form=search_uchastnik_form %}
    {% endif %}

    {% block content %}
    {% if person_name %}
    <span>Hello! {{ person_name }}</span>
    {% endif %}
    {% endblock %}
  </body>
</html>

templates/search.html
{% extends 'index.html' %}

{% block title %}Search{% endblock %}

{% block content %}
{% if queryset %}
<table class="table">
  <thead>
    <tr>
      <th>Uchastnik</th>
      <th>StoronaPoDeluCount</th>
    </tr>
  </thead>
  <tbody>
    {% for value in queryset %}
    <tr>
      <td>{{ value.uchastnik }}</td>
      <td>{{ value.storonapodelu_set.count }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock %}